adminapp/urls.py
from django.urls import path
import adminapp.views as adminapp

app_name = 'adminapp'

urlpatterns = [
    path('', adminapp.index, name = 'index'),
    # path('users/', adminapp.admin_users, name = 'admin_users'),
    path('users/', adminapp.UserListView.as_view(), name='admin_users'),
    # path('users/create', adminapp.admin_users_create, name = 'admin_users_create'),
    path('users/create', adminapp.UserCreateView.as_view(), name='admin_users_create'),
    # path('users/update/<int:user_id>/', adminapp.admin_users_update, name = 'admin_users_update'),
    path('users/update/<int:pk>/', adminapp.UserUpdateView.as_view(), name='admin_users_update'),
    # path('users/remove/<int:user_id>/', adminapp.admin_users_remove, name = 'admin_users_remove'),
    path('users/remove/<int:pk>/', adminapp.UserDeleteView.as_view(), name='admin_users_remove'),
    # path('products/', adminapp.admin_products, name = 'admin_products'),
    path('products/', adminapp.ProductListView.as_view(), name='admin_products'),
    path('products/create', adminapp.admin_products_create, name = 'admin_products_create'),
    path('products/update/<int:product_id>/', adminapp.admin_products_update, name = 'admin_products_update'),
    path('products/remove/<int:product_id>/', adminapp.admin_products_remove, name = 'admin_products_remove'),
    # path('categories/', adminapp.admin_categories, name='admin_categories'),
    path('categories/', adminapp.CategoryListView.as_view(), name='admin_categories'),
    path('categories/create', adminapp.admin_categories_create, name='admin_categories_create'),
    path('categories/update/<int:cat_id>/', adminapp.admin_categories_update, name='admin_categories_update'),
    path('categories/remove/<int:cat_id>/', adminapp.admin_categories_remove, name='admin_categories_remove'),


]

authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name = 'login'),
    path('register/', authapp.register, name = 'register'),
    path('logout/', authapp.logout, name='logout'),
    path('profile/', authapp.profile, name = 'profile'),

]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from mainapp import views as mainapp_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', mainapp_views.index, name='main'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('baskets/', include('basketapp.urls', namespace='baskets')),
    path('admin-staff/', include('adminapp.urls', namespace='admin_staff')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path

import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.products, name='index'),
    path('<int:category_id>/', mainapp.products, name='product'),
    path('page/<int:page>/', mainapp.products, name='page'),
]

adminapp/models.py
from django.db import models

# Create your models here.

adminapp/forms.py
from authapp.forms import UserRegisterForm, UserProfileForm
from authapp.models import User
from mainapp.models import ProductCategory, Product
from django import forms


class UserAdminRegisterForm(UserRegisterForm):
    avatar = forms.ImageField(widget=forms.FileInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2', 'avatar')

    def __init__(self, *args, **kwargs):
        super(UserAdminRegisterForm, self).__init__(*args, **kwargs)
        self.fields['avatar'].widget.attrs['class'] = 'custom-file-input'


class UserAdminProfileForm(UserProfileForm):

    def __init__(self, *args, **kwargs):
        super(UserAdminProfileForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['readonly'] = False
        self.fields['email'].widget.attrs['readonly'] = False


class ProductAdminRegisterForm(forms.ModelForm):
    image = forms.ImageField(widget=forms.FileInput())

    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(ProductAdminRegisterForm, self).__init__(*args, **kwargs)
        self.fields['image'].widget.attrs['class'] = 'custom-file-input'
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''
        self.fields['image'].widget.attrs['class'] = 'custom-file-input'


class ProductAdminChangeForm(forms.ModelForm):
    image = forms.ImageField(widget=forms.FileInput())

    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(ProductAdminChangeForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control py-4'
        self.fields['image'].widget.attrs['class'] = 'custom-file-input'



class CategoryAdminRegisterForm(forms.ModelForm):

    class Meta:
        model = ProductCategory
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(CategoryAdminRegisterForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''



class CategoryAdminChangeForm(forms.ModelForm):

    class Meta:
        model = ProductCategory
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(CategoryAdminChangeForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control py-4'

adminapp/views.py
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404
from authapp.models import User
from adminapp.forms import UserAdminRegisterForm, UserAdminProfileForm, ProductAdminRegisterForm, ProductAdminChangeForm,CategoryAdminRegisterForm,CategoryAdminChangeForm
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import user_passes_test
from mainapp.models import ProductCategory, Product

from django.views.generic.list import ListView
from django.utils.decorators import method_decorator
from django.views.generic.edit import CreateView, UpdateView, DeleteView


# Create your views here.
@user_passes_test(lambda u: u.is_superuser)
def index(request):
    return render(request, 'adminapp/index.html')

class UserListView(ListView):
    model = User
    template_name = 'adminapp/admin-users-read.html'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super(UserListView, self).dispatch(request, *args, **kwargs)



# @user_passes_test(lambda u: u.is_superuser)
# def admin_users(request):
#     context = {
#         'users': User.objects.all(),
#     }
#     return render(request, 'adminapp/admin-users-read.html', context)

class UserCreateView(CreateView):
    model = User
    template_name = 'adminapp/admin-users-create.html'
    success_url = reverse_lazy('adminapp:admin_users')
    form_class = UserAdminRegisterForm

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super(UserCreateView, self).dispatch(request, *args, **kwargs)



# @user_passes_test(lambda u: u.is_superuser)
# def admin_users_create(request):
#     if request.method == 'POST':
#         form = UserAdminRegisterForm(data=request.POST, files=request.FILES)
#         if form.is_valid():
#             form.save()
#             return HttpResponseRedirect(reverse('adminapp:admin_users'))
#     else:
#         form = UserAdminRegisterForm()
#     context = {'form': form}
#     return render(request, 'adminapp/admin-users-create.html', context)


# @user_passes_test(lambda u: u.is_superuser)
# def admin_users_update(request, user_id):
#     user = User.objects.get(id=user_id)
#     if request.method == 'POST':
#         form = UserAdminProfileForm(data=request.POST, files=request.FILES, instance=user)
#         if form.is_valid():
#             form.save()
#             return HttpResponseRedirect(reverse('admin_staff:admin_users'))
#     else:
#         form = UserAdminProfileForm(instance=user)
#
#     context = {
#         'form': form,
#         'user': user
#     }
#     return render(request, 'adminapp/admin-users-update-delete.html', context)


class UserUpdateView(UpdateView):
    model = User
    template_name = 'adminapp/admin-users-update-delete.html'
    success_url = reverse_lazy('adminapp:admin_users')
    form_class = UserAdminProfileForm

    def get_context_data(self, **kwargs):
        context= super(UserUpdateView,self).get_context_data(**kwargs)
        context['title'] = 'GeekShop USER UPDATE'
        return context



#
# @user_passes_test(lambda u: u.is_superuser)
# def admin_users_remove(request, user_id):
#     user = User.objects.get(id=user_id)
#     user.is_active = False
#     user.save()
#     return HttpResponseRedirect(reverse('admin_staff:admin_users'))

class UserDeleteView(DeleteView):
    model = User
    template_name = 'adminapp/admin-users-update-delete.html'
    success_url = reverse_lazy('adminapp:admin_users')


    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())




# def admin_products(request):
#     context = {
#         'products': Product.objects.all(),
#     }
#     # product = get_object_or_404(Product, pk=pk)
#     # context = {'product': product, }
#     return render(request, 'adminapp/admin-product-read.html', context)


class ProductListView(ListView):
    model = Product
    template_name = 'adminapp/admin-product-read.html'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super(ProductListView, self).dispatch(request, *args, **kwargs)



def admin_products_create(request):
    if request.method == 'POST':
        form = ProductAdminRegisterForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('adminapp:admin_products'))
    else:
        form = ProductAdminRegisterForm()
    context = {'form': form}
    # category = get_object_or_404(ProductCategory, pk=pk)
    # if request.method == 'POST':
    #     form = ProductAdminRegisterForm(data=request.POST, files=request.FILES)
    #     if form.is_valid():
    #         form.save()
    #         return HttpResponseRedirect(reverse('adminapp:admin_products', args=[pk]))
    # else:
    #     form = ProductAdminRegisterForm()
    # content = {
    #     'form': form,
    #     'category': category,
    # }

    return render(request, 'adminapp/admin-products-create.html', context)


def admin_products_update(request, product_id):
    product = Product.objects.get(id=product_id)
    if request.method == 'POST':
        form = ProductAdminChangeForm(data=request.POST, files=request.FILES, instance=product)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('admin_staff:admin_products'))
    else:
        form = ProductAdminChangeForm(instance=product)

    context = {
        'form': form,
        'product': product
    }
    return render(request, 'adminapp/admin-products-update-delete.html', context)


def admin_products_remove(request, product_id):
    product = Product.objects.get(id=product_id)
    product.is_active = False
    product.save()
    return HttpResponseRedirect(reverse('admin_staff:admin_products'))

# def admin_products_update(request, pk):
#     product = get_object_or_404(Product, pk=pk)
#
#     if request.method == 'POST':
#         form = ProductAdminChangeForm(request.POST, request.FILES,
#                                       instance=product)
#         if form.is_valid():
#             form.save()
#             return HttpResponseRedirect(reverse('admin_staff:admin_products',
#                                                 args=[product.pk]))
#     else:
#         form = ProductAdminChangeForm(instance=product)
#
#     content = {'form': form,
#                'category': product.category
#                }
#
#     return render(request, 'adminapp/admin-products-update-delete.html', content)


# def admin_products_remove(request, pk):
#     product = get_object_or_404(Product, pk=pk)
#     product.is_active = False
#     product.save()
#     return HttpResponseRedirect(reverse('admin_staff:admin_products', args=[product.category.pk]))
# def admin_categories(request):
#     context = {
#         'categories': ProductCategory.objects.all(),
#     }
#     return render(request, 'adminapp/admin-category-read.html', context)


class CategoryListView(ListView):
    model = ProductCategory
    template_name = 'adminapp/admin-category-read.html'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super(CategoryListView, self).dispatch(request, *args, **kwargs)


def admin_categories_create(request):
    if request.method == 'POST':
        form = CategoryAdminRegisterForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('adminapp:admin_categories'))
    else:
        form = CategoryAdminRegisterForm()
    context = {'form': form}
    return render(request, 'adminapp/admin-category-create.html', context)


def admin_categories_remove(request, cat_id):
    category = ProductCategory.objects.get(id=cat_id)
    category.is_active = False
    category.save()
    return HttpResponseRedirect(reverse('admin_staff:admin_categories'))



def admin_categories_update(request, cat_id):
    category = ProductCategory.objects.get(id=cat_id)
    if request.method == 'POST':
        form = CategoryAdminChangeForm(data=request.POST, files=request.FILES, instance=category)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('admin_staff:admin_categories'))
    else:
        form = CategoryAdminChangeForm(instance=category)

    context = {
        'form': form,
        'category': category
    }
    return render(request, 'adminapp/admin-category-update-delete.html', context)

adminapp/templates/adminapp/admin-category-create.html
{% extends 'adminapp/base.html' %}

{% block content %}
    <h1 class="mt-4">Создание категории</h1>
    <form action="{% url 'admin_staff:admin_categories_create'  %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-row">
            <div class="col-lg-6">
                <div class="form-group">
                    <label class="small mb-1" for="{{ form.name.id_for_label }}">Название</label>
                    {{ form.name }}
                </div>
            </div>
            <div class="col-lg-6">
                <div class="form-group">
                    <label class="small mb-1" for="{{ form.description.id_for_label }}">Описание</label>
                    {{ form.description }}
                </div>
            </div>
        </div>
        <div class="form-row">
            <div class="col-lg-12" style="margin-top: 33px;">
                <input class="btn btn-info btn-block" type="submit" value="Сохранить">
            </div>
        </div>
        </div>
    </form>
{% endblock %}

adminapp/templates/adminapp/admin-category-read.html
{% extends 'adminapp/base.html' %}

{% block content %}
                <h1 class="mt-4">Категории</h1>
    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-table mr-1"></i>
            Категории
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                    <tr>
                        <th>Название</th>
                        <th>Краткое описание</th>
                        <th>Активен</th>
                    </tr>
                    </thead>
                    <tfoot>
                    <tr>
                        <th>Название</th>
                        <th>Краткое описание</th>
                        <th>Активен</th>
                    </tr>
                    </tfoot>
                    <tbody>
                    {% for category in object_list %}
                        <tr>
                            <td>
                                <a href="{% url 'admin_staff:admin_categories_update'  category.id%} "  style="color: dodgerblue">
                                    {{ category.name }}
                                </a>
                            </td>
                            <td>{{ category.description }}</td>
                        <td class="text-center">
                                {% if category.is_active %}
                                    <i class="fas fa-check-circle"></i>
                                {% else %}
                                    <i class="fas fa-times-circle"></i>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div class="card-footer">
            <button class="btn btn-success">
                <a href="{% url 'admin_staff:admin_categories_create'%}" style="color: white;">
                    Создать категорию
                </a>
            </button>
        </div>
    </div>
{% endblock %}

adminapp/templates/adminapp/admin-category-update-delete.html
{% extends 'adminapp/base.html' %}

{% block content %}
    <h1 class="mt-4">Редактирование  | {{ category.name }}</h1>
    <div class="card-body">
    <form action="{% url 'admin_staff:admin_categories_update' category.id %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-row">
            <div class="col-lg-6">
                <div class="form-group">
                    <label class="small mb-1" for="{{ form.name.id_for_label }}">Название</label>
                    {{ form.name }}
                </div>
            </div>
            <div class="col-lg-6">
                <div class="form-group">
                    <label class="small mb-1" for="{{ form.description.id_for_label }}">Описание</label>
                    {{ form.description }}
                </div>
            </div>
        </div>

        <div class="form-row">
        <div class="form-row">
            <div class="col-lg-12" style="margin-top: 33px;">
                <input class="btn btn-info btn-block" type="submit" value="Сохранить">
            </div>
        </div>
        </div>
    </form>
        <div class="row">
            <div class="col-lg-12" style="margin-top: 33px;">
                <a href="{% url 'admin_staff:admin_categories_remove' category.id %}">
                    <input class="btn btn-danger btn-block" type="submit" value="Удалить">
                </a>
            </div>
        </div>
    </div>
{% endblock %}

adminapp/templates/adminapp/admin-product-read.html
{% extends 'adminapp/base.html' %}

{% block content %}
                <h1 class="mt-4">Продукты</h1>
    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-table mr-1"></i>
            Продукты
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                    <tr>
                        <th>Название</th>
                        <th>Описание</th>
                        <th>Краткое описание</th>
                        <th>Фото</th>
                        <th>Цена</th>
                        <th>Категория</th>
                        <th>Активен</th>
                    </tr>
                    </thead>
                    <tfoot>
                    <tr>
                        <th>Название</th>
                        <th>Описание</th>
                        <th>Краткое описание</th>
                        <th>Фото</th>
                        <th>Цена</th>
                        <th>Категория</th>
                        <th>Активен</th>
                    </tr>
                    </tfoot>
                    <tbody>
                    {% for product in object_list %}
                        <tr>
                            <td>
                                <a href="{% url 'admin_staff:admin_products_update'  product.id %} " style="color: dodgerblue">
                                    {{ product.name }}
                                </a>
                            </td>
                            <td>{{ product.description }}</td>
                            <td>{{ product.short_description }}</td>
                            <td><img class="card-img-top"
                                    src="/media/{{product.image}}"
                                    alt=""></td>
                            <td class="text-center">
                                {{ product.price }}
                            </td>
                            <td class="text-center">
                                {{ product.category }}
                            </td>
                        <td class="text-center">
                                {% if product.is_active %}
                                    <i class="fas fa-check-circle"></i>
                                {% else %}
                                    <i class="fas fa-times-circle"></i>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div class="card-footer">
            <button class="btn btn-success">
                <a href="{% url 'admin_staff:admin_products_create'  %}" style="color: white;">
                    Создать продукт
                </a>
            </button>
        </div>
    </div>
{% endblock %}

adminapp/templates/adminapp/admin-products-update-delete.html
{% extends 'adminapp/base.html' %}

{% block content %}
    <h1 class="mt-4">Редактирование  | {{ product.name }}</h1>
    <div class="card-body">
    <form action="{% url 'admin_staff:admin_products_update' product.id %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-row">
            <div class="col-lg-6">
                <div class="form-group">
                    <label class="small mb-1" for="{{ form.name.id_for_label }}">Название</label>
                    {{ form.name }}
                </div>
            </div>
            <div class="col-lg-6">
                <div class="form-group">
                    <label class="small mb-1" for="{{ form.description.id_for_label }}">Описание</label>
                    {{ form.description }}
                </div>
            </div>
        </div>
         <div class="col-lg-6">
                <div class="form-group">
                    <label class="small mb-1" for="{{ form.short_description.id_for_label }}">Краткое описание</label>
                    {{ form.short_description }}
                </div>
            </div>

        <div class="form-row mb-2">
            <div class="col-lg-12">
                <div class="custom-file">
                    {{ form.image }}
                    <label class="custom-file-label" for="{{ form.image.id_for_label }}">Выберите изображение</label>
                </div>
            </div>
        </div>
        <div class="form-row">
            <div class="col-lg-6">
                <label class="small mb-1" for="{{ form.price.id_for_label }}">Цена</label>
                {{ form.price }}
            </div>
            <div class="col-lg-6">
                <label class="small mb-1" for="{{ form.quantity.id_for_label }}">Количество
                    </label>
                {{ form.quantity }}
            </div>
        </div>
        <div class="form-row">
            <div class="col-lg-6">
                <label class="small mb-1" for="{{ form.category.id_for_label }}">Категория</label>
                {{ form.category }}
            </div>
        <div class="form-row">
            <div class="col-lg-12" style="margin-top: 33px;">
                <input class="btn btn-info btn-block" type="submit" value="Сохранить">
            </div>
        </div>
        </div>
    </form>
        <div class="row">
            <div class="col-lg-12" style="margin-top: 33px;">
                <a href="{% url 'admin_staff:admin_products_remove' product.id %}">
                    <input class="btn btn-danger btn-block" type="submit" value="Удалить">
                </a>
            </div>
        </div>
    </div>
{% endblock %}

adminapp/templates/adminapp/admin-users-read.html
{% extends 'adminapp/base.html' %}

{% block content %}
                <h1 class="mt-4">Пользователи</h1>
    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-table mr-1"></i>
            Пользователи
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                    <tr>
                        <th>Имя пользователя</th>
                        <th>Имя</th>
                        <th>Фамилия</th>
                        <th>Адрес эл. почты</th>
                        <th>Персонал сайта</th>
                        <th>Активный</th>
                    </tr>
                    </thead>
                    <tfoot>
                    <tr>
                        <th>Имя пользователя</th>
                        <th>Имя</th>
                        <th>Фамилия</th>
                        <th>Адрес эл. почты</th>
                        <th>Персонал сайта</th>
                        <th>Активный</th>
                    </tr>
                    </tfoot>
                    <tbody>
                    {% for user in object_list %}
                        <tr>
                            <td>
                                <a href="{% url 'admin_staff:admin_users_update' user.id %}" style="color: dodgerblue">
                                    {{ user.username }}
                                </a>
                            </td>
                            <td>{{ user.first_name }}</td>
                            <td>{{ user.last_name }}</td>
                            <td>{{ user.email }}</td>
                            <td class="text-center">
                                {% if user.is_staff %}
                                    <i class="fas fa-check-circle"></i>
                                {% else %}
                                    <i class="fas fa-times-circle"></i>
                                {% endif %}
                            </td>
                            <td class="text-center">
                                {% if user.is_active %}
                                    <i class="fas fa-check-circle"></i>
                                {% else %}
                                    <i class="fas fa-times-circle"></i>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div class="card-footer">
            <button class="btn btn-success">
                <a href="{% url 'admin_staff:admin_users_create' %}" style="color: white;">
                    Создать пользователя
                </a>
            </button>
        </div>
    </div>
{% endblock %}

adminapp/templates/adminapp/admin-users-update-delete.html
{% extends 'adminapp/base.html' %}

{% block content %}
    <h1 class="mt-4">Редактирование пользователя | {{ user.username }}</h1>
    <div class="card-body">
        <form action="{% url 'admin_staff:admin_users_update' user.id %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-row">
                <div class="col-lg-6">
                    <div class="form-group">
                        <label class="small mb-1" for="{{ form.first_name.id_for_label }}">Имя</label>
                        {{ form.first_name }}
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="form-group">
                        <label class="small mb-1" for="{{ form.last_name.id_for_label }}">Фамилия</label>
                        {{ form.last_name }}
                    </div>
                </div>
            </div>
            <div class="form-row mb-2">
                <div class="col-lg-12">
                    <div class="custom-file">
                        {{ form.avatar }}
                        <label class="custom-file-label" for="{{ form.avatar.id_for_label }}">Выберите
                            изображение</label>
                    </div>
                </div>
            </div>
            <div class="form-row">
                <div class="col-lg-6">
                    <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя пользователя</label>
                    {{ form.username }}
                </div>
                <div class="col-lg-6">
                    <label class="small mb-1" for="{{ form.email.id_for_label }}">Адрес электронной
                        почты</label>
                    {{ form.email }}
                </div>
            </div>
            <div class="form-row">
                <div class="col-lg-12" style="margin-top: 33px;">
                    <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                </div>
            </div>
        </form>

                <div class="row">
            <div class="col-lg-12" style="margin-top: 33px;">
                <form action="{% url 'admin_staff:admin_users_remove' user.id %}" method="post">
                    {% csrf_token %}
                    <input class="btn btn-danger btn-block" type="submit" value="Удалить">
                </form>
            </div>
        </div>

    </div>
{% endblock %}

adminapp/templates/adminapp/index.html
{% extends 'adminapp/base.html' %}

{% block content %}

<h1 class="mt-4">Административная панель</h1>

{% endblock %}